apiVersion: v1
kind: Namespace
metadata:
  name: local-llm
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: local-llm
    meta.helm.sh/release-namespace: local-llm
