apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "ghcr.io/open-webui/open-webui:main"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: WEBUI_CORS_PROXY_ENABLED
              value: "true"
            - name: WEBUI_DATABASE_PATH
              value: "/app/backend/data/webui.db"
            - name: WEBUI_HOST
              value: "0.0.0.0"
            - name: WEBUI_PORT
              value: "8080"
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "200m"
          volumeMounts:
            - name: frontend-data
              mountPath: /app/backend/data
      volumes:
        - name: frontend-data
          persistentVolumeClaim:
            claimName: frontend-data
