apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "ghcr.io/open-webui/open-webui:main"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: OLLAMA_API_BASE_URL
              value: "http://ollama:11434"
            - name: WEBUI_SECRET_KEY
              value: "local-llm-secret"
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "200m"
