apiVersion: v1
kind: Service
metadata:
  name: ollama
spec:
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
  selector:
    app: ollama
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - ollama pull phi4
          ports:
            - containerPort: 11434
          resources:
            limits:
              memory: "16Gi"
              cpu: "8"
            requests:
              memory: "8Gi"
              cpu: "4"
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 10Gi
